### ISSUE TITLE
Sorry! An error occurred while processing your request.

### ISSUE THREAD

**Issue by ghost** [gta5-map/Social-Club-example-parser#3] opened 2015-04-11 16:07 UTC
I've tried the parser on localhost and on a web server, but the script doesn't work correctly.

With a correct username: "Sorry! An error occurred while processing your request.".
http://i.imgur.com/kXk8JU6.jpg

With a non existing username, correct page but without data (seems legit)
http://i.imgur.com/a3TGMqe.jpg

__RequestVerificationToken is ok.

Any suggestion?

**Comment by frdmn** [comment] 2015-04-20 13:53
@hacklover Crud. Forgot to get back to you via IRC. Any news about this issue?

**Comment by Naoto-Ida** [comment] 2015-05-07 02:55
Simular situation. I'm guessing with the PC release, they added a few parameters to the cookies to secure it better. @frdmn , do you know if "uacdlftm" existed when you wrote this? I will test it out.

**Comment by frdmn** [comment] 2015-05-07 05:57
@Naoto-Ida @hacklover I'll see if I can reproduce the issue on the weekend.

**Comment by Naoto-Ida** [comment] 2015-05-07 06:46
Thanks @frdmn, I'll try to solve it too. Although, I am planning on making a Java version of this.

**Comment by frdmn** [comment] 2015-05-07 06:50
@Naoto-Ida Nice! I assume the language is not relevant in this case. If Rockstar changed anything in their end, I assume all parser will fail.

**Comment by Naoto-Ida** [comment] 2015-05-07 08:04
@frdmn It's definitely not anything that is POSTed, it is something to do with modifying the cookies. Will look into it and report.

**Comment by frdmn** [comment] 2015-05-07 10:12
@hacklover Can you pull from master and retry using @Naoto-Ida's fix?

**Comment by frdmn** [comment] 2015-08-27 14:25
Closing for now, since I didnt hear anything from @hacklover

**Closed as completed by frdmn** 2015-08-27 14:25 UTC
